kind: pipeline
name: default
type: docker

steps:
  - name: hello-world
    image: node:14-slim
    commands:
      - echo "hello world"

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock