kind: pipeline
name: default
type: docker

steps:
  - name: jest
    image: node:14-slim
    commands:
      - npm i
      - npm run test

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock